use super::*;

pub(super) const fn profile() -> PlatformComponentProfile {
    PlatformComponentProfile {
        style: ZsPlatformStyle::Gtk,
        #[cfg(feature = "label")]
        section: PlatformSectionProfile {
            composition: PlatformSectionComposition::GtkBoxedList,
            heading_color: ColorRole::PrimaryText,
        },
        #[cfg(feature = "label")]
        navigation: PlatformNavigationProfile {
            composition: PlatformNavigationComposition::GtkBoxedSidebar,
            behavior: PlatformNavigationBehavior::GtkAdaptive,
            title_role: TextRole::Body,
            preferred_pane_width: Dp::new(280.0),
            horizontal_inset: Dp::new(32.0),
            pane_color: ColorRole::Surface,
            scrim_alpha: 48,
            toggle_icon_size: Dp::new(16.0),
        },
        #[cfg(feature = "button")]
        button: PlatformButtonProfile {
            fill: ColorRole::SurfaceRaised,
            stroke: Some(ColorRole::Border),
        },
        #[cfg(feature = "button")]
        command_bar: PlatformCommandBarProfile {
            bar_height: Dp::new(34.0),
            button_height: Dp::new(34.0),
            icon_size: Dp::new(16.0),
            content_gap: Dp::new(6.0),
            item_gap: Dp::new(6.0),
            label_role: TextRole::Button,
        },
        #[cfg(feature = "tabs")]
        tabs: PlatformTabProfile {
            composition: PlatformTabComposition::GtkTabBar,
            metrics: ZsTabViewMetrics {
                strip_height: Dp::new(42.0),
                header_top_padding: Dp::new(4.0),
                item_height: Dp::new(34.0),
                outer_inset: Dp::new(6.0),
                item_gap: Dp::new(0.0),
                horizontal_padding: Dp::new(12.0),
                icon_size: Dp::new(16.0),
                icon_gap: Dp::new(8.0),
                minimum_item_width: Dp::new(72.0),
                maximum_item_width: Dp::new(220.0),
                radius: Dp::new(8.0),
                selection_indicator_height: Dp::new(0.0),
            },
            label_role: TextRole::Button,
            arrow_selects: false,
            supports_home_end_focus: true,
            cycle_shortcut: PlatformTabCycleShortcut::ControlPage,
        },
        #[cfg(feature = "dialog")]
        dialog: PlatformDialogProfile {
            composition: PlatformDialogComposition::GtkTrailingActions,
            metrics: ZsContentDialogMetrics {
                minimum_width: Dp::new(340.0),
                maximum_width: Dp::new(480.0),
                viewport_margin: Dp::new(24.0),
                content_padding: Dp::new(24.0),
                title_gap: Dp::new(8.0),
                action_gap: Dp::new(24.0),
                button_gap: Dp::new(8.0),
                button_height: Dp::new(34.0),
                minimum_button_width: Dp::new(86.0),
                surface_radius: Dp::new(12.0),
                button_radius: Dp::new(6.0),
            },
            scrim_alpha: 104,
            estimated_glyph_width: Dp::new(8.0),
            estimated_label_padding: Dp::new(28.0),
        },
        shell: PlatformShellProfile {
            style: ZsPlatformStyle::Gtk,
            navigation: PlatformShellNavigationComposition::GtkSidebar,
            sections: PlatformShellSectionComposition::GtkBoxedLists,
            preferred_navigation_width: Dp::new(280.0),
            top_height: Dp::new(64.0),
            navigation_start: Dp::new(52.0),
            content_gap: Dp::new(32.0),
            content_top_gap: Dp::new(16.0),
            viewport_mask_height: Dp::new(8.0),
            scrollbar_width: Dp::new(6.0),
            active_scrollbar_width: Dp::new(8.0),
            scrollbar_margin: Dp::new(6.0),
            section_header_height: Dp::new(30.0),
            section_row_height: Dp::new(40.0),
            section_row_gap: Dp::new(1.0),
            section_gap: Dp::new(18.0),
            section_horizontal_padding: Dp::new(12.0),
            section_height_extra: Dp::new(24.0),
            section_body_bottom_inset: Dp::new(12.0),
            navigation_item_height: Dp::new(36.0),
            navigation_item_stride: Dp::new(40.0),
            navigation_item_inset: Dp::new(12.0),
            navigation_item_radius: Dp::new(6.0),
            section_radius: Dp::new(12.0),
            title_x: Dp::new(32.0),
            title_y: Dp::new(18.0),
            title_width: Dp::new(360.0),
            title_height: Dp::new(28.0),
            menu_icon_x: Dp::new(0.0),
            menu_icon_y: Dp::new(0.0),
            menu_icon_size: Dp::new(0.0),
            show_menu_icon: false,
            app_title_x: Dp::new(16.0),
            app_title_y: Dp::new(16.0),
            app_title_width: Dp::new(248.0),
            app_title_height: Dp::new(24.0),
            action_margin: Dp::new(18.0),
            action_height: Dp::new(34.0),
            primary_action_width: Dp::new(84.0),
            secondary_action_width: Dp::new(76.0),
            action_gap: Dp::new(8.0),
            draw_row_separators: true,
        },
    }
}
