use super::*;

pub(super) const fn profile() -> PlatformComponentProfile {
    PlatformComponentProfile {
        style: ZsPlatformStyle::Macos,
        style_tokens: PlatformStyleTokenProfile {
            radius: ZsuiRadiusTokens {
                small: Dp::new(5.0),
                medium: Dp::new(6.0),
                large: Dp::new(10.0),
                pill: Dp::new(999.0),
            },
            spacing: ZsuiSpacingTokens {
                xs: Dp::new(2.0),
                sm: Dp::new(6.0),
                md: Dp::new(8.0),
                lg: Dp::new(12.0),
                xl: Dp::new(20.0),
                content_gap: Dp::new(8.0),
                content_padding: Dp::new(12.0),
                page_padding: Dp::new(20.0),
            },
            controls: ZsuiControlMetrics {
                compact_height: Dp::new(22.0),
                standard_height: Dp::new(28.0),
                touch_target: Dp::new(32.0),
                navigation_row_height: Dp::new(28.0),
                small_icon: Dp::new(16.0),
                standard_icon: Dp::new(16.0),
            },
        },
        typography: PlatformTypographyProfile {
            body: ZsTypographyMetrics::new(13.0, 16.0, TextWeight::Regular),
            caption: ZsTypographyMetrics::new(10.0, 13.0, TextWeight::Regular),
            body_large: ZsTypographyMetrics::new(15.0, 20.0, TextWeight::Regular),
            subtitle: ZsTypographyMetrics::new(17.0, 22.0, TextWeight::Regular),
            title: ZsTypographyMetrics::new(22.0, 26.0, TextWeight::Regular),
            title_large: ZsTypographyMetrics::new(26.0, 32.0, TextWeight::Regular),
            display: ZsTypographyMetrics::new(26.0, 32.0, TextWeight::Regular),
            button: ZsTypographyMetrics::new(13.0, 16.0, TextWeight::Regular),
            icon: ZsTypographyMetrics::new(16.0, 20.0, TextWeight::Regular),
            monospace: ZsTypographyMetrics::new(13.0, 16.0, TextWeight::Regular),
            fallback: PlatformTypographyFallbackProfile {
                source: "appkit_semantic_fallback",
                ui_font_family: ".AppleSystemUIFont",
                small_font_family: ".AppleSystemUIFont",
                display_font_family: ".AppleSystemUIFont",
                monospace_font_family: "Menlo",
                icon_font_family: ".AppleSystemUIFont",
                rasterization: "appkit_nsstring_coretext",
            },
        },
        focus_visuals: PlatformFocusVisualProfile {
            text_input_indicator_height: None,
            outline_inset: Dp::new(1.0),
            outline_width: Dp::new(2.0),
        },
        base_control: PlatformBaseControlProfile {
            metrics: ZsBaseControlMetrics {
                body_line_height: Dp::new(16.0),
                average_character_width: Dp::new(6.8),
                button_minimum_width: Dp::new(82.0),
                button_height: Dp::new(28.0),
                button_radius: Dp::new(6.0),
                button_padding_left: Dp::new(12.0),
                button_padding_top: Dp::new(4.0),
                button_padding_right: Dp::new(12.0),
                button_padding_bottom: Dp::new(4.0),
                text_input_minimum_width: Dp::new(72.0),
                text_input_height: Dp::new(28.0),
                text_input_radius: Dp::new(5.0),
                text_input_padding_left: Dp::new(7.0),
                text_input_padding_top: Dp::new(4.0),
                text_input_padding_right: Dp::new(7.0),
                text_input_padding_bottom: Dp::new(4.0),
                check_minimum_width: Dp::new(82.0),
                check_height: Dp::new(22.0),
                check_indicator_size: Dp::new(14.0),
                toggle_width: Dp::new(42.0),
                toggle_height: Dp::new(28.0),
                toggle_track_width: Dp::new(36.0),
                toggle_track_height: Dp::new(20.0),
                toggle_knob_off_size: Dp::new(16.0),
                toggle_knob_on_size: Dp::new(16.0),
                slider_minimum_width: Dp::new(96.0),
                slider_height: Dp::new(28.0),
                slider_track_height: Dp::new(3.0),
                slider_thumb_size: Dp::new(14.0),
                radio_minimum_width: Dp::new(82.0),
                radio_height: Dp::new(22.0),
                radio_indicator_size: Dp::new(16.0),
                radio_dot_size: Dp::new(6.0),
                progress_slot_height: Dp::new(12.0),
                progress_track_height: Dp::new(3.0),
                selection_minimum_width: Dp::new(96.0),
                selection_height: Dp::new(28.0),
                time_picker_minimum_width: Dp::new(120.0),
            },
        },
        #[cfg(feature = "label")]
        section: PlatformSectionProfile {
            composition: PlatformSectionComposition::AppKitForm,
            heading_color: ColorRole::SecondaryText,
        },
        #[cfg(feature = "label")]
        navigation: PlatformNavigationProfile {
            composition: PlatformNavigationComposition::AppKitSourceList,
            behavior: PlatformNavigationBehavior::AppKitSplitView,
            title_role: TextRole::Body,
            preferred_pane_width: Dp::new(240.0),
            horizontal_inset: Dp::new(24.0),
            pane_color: ColorRole::SurfaceRaised,
            scrim_alpha: 32,
            toggle_icon_size: Dp::new(16.0),
        },
        #[cfg(feature = "button")]
        button: PlatformButtonProfile {
            fill: ColorRole::Control,
            stroke: None,
            navigation_item: PlatformNavigationItemProfile {
                composition: PlatformNavigationItemComposition::AppKitSourceListRow,
                metrics: ZsNavigationItemMetrics {
                    open_pane_width: Dp::new(240.0),
                    item_height: Dp::new(28.0),
                    icon_size: Dp::new(16.0),
                    icon_box_width: Dp::new(28.0),
                    text_leading_margin: Dp::new(4.0),
                    trailing_padding: Dp::new(8.0),
                    indicator_width: Dp::new(0.0),
                    indicator_height: Dp::new(0.0),
                    indicator_radius: Dp::new(0.0),
                    radius: Dp::new(6.0),
                },
            },
        },
        #[cfg(feature = "button")]
        command_bar: PlatformCommandBarProfile {
            bar_height: Dp::new(28.0),
            button_height: Dp::new(28.0),
            icon_size: Dp::new(16.0),
            content_gap: Dp::new(6.0),
            item_gap: Dp::new(6.0),
            label_role: TextRole::Button,
        },
        #[cfg(feature = "tabs")]
        tabs: PlatformTabProfile {
            composition: PlatformTabComposition::AppKitSegmented,
            metrics: ZsTabViewMetrics {
                strip_height: Dp::new(32.0),
                header_top_padding: Dp::new(0.0),
                item_height: Dp::new(32.0),
                content_padding: Dp::new(12.0),
                outer_inset: Dp::new(12.0),
                item_gap: Dp::new(0.0),
                horizontal_padding: Dp::new(14.0),
                icon_size: Dp::new(14.0),
                icon_gap: Dp::new(6.0),
                minimum_item_width: Dp::new(72.0),
                maximum_item_width: Dp::new(160.0),
                radius: Dp::new(6.0),
                selection_indicator_height: Dp::new(0.0),
            },
            label_role: TextRole::Button,
            arrow_selects: true,
            supports_home_end_focus: false,
            cycle_shortcut: PlatformTabCycleShortcut::None,
        },
        #[cfg(feature = "dialog")]
        dialog: PlatformDialogProfile {
            composition: PlatformDialogComposition::AppKitTrailingActions,
            metrics: ZsContentDialogMetrics {
                minimum_width: Dp::new(360.0),
                maximum_width: Dp::new(480.0),
                viewport_margin: Dp::new(28.0),
                content_padding: Dp::new(20.0),
                title_gap: Dp::new(8.0),
                action_gap: Dp::new(20.0),
                button_gap: Dp::new(8.0),
                button_height: Dp::new(28.0),
                minimum_button_width: Dp::new(82.0),
                surface_radius: Dp::new(12.0),
                button_radius: Dp::new(6.0),
            },
            scrim_alpha: 56,
            estimated_glyph_width: Dp::new(7.0),
            estimated_label_padding: Dp::new(28.0),
        },
        #[cfg(feature = "flyout")]
        flyout: PlatformFlyoutProfile {
            composition: PlatformFlyoutComposition::AppKitPopover,
            viewport_margin: Dp::new(12.0),
            content_padding: Dp::new(16.0),
            surface_radius: Dp::new(10.0),
            target_gap: Dp::new(4.0),
            tail_size: Dp::new(10.0),
            shadow_offset: Dp::new(2.0),
            shadow_alpha: 26,
            automatic_placement: crate::ZsFlyoutPlacement::Right,
        },
        #[cfg(feature = "menu-flyout")]
        menu_flyout: PlatformMenuFlyoutProfile {
            metrics: ZsMenuFlyoutMetrics {
                minimum_width: Dp::new(176.0),
                maximum_width: Dp::new(360.0),
                viewport_margin: Dp::new(8.0),
                target_gap: Dp::new(3.0),
                surface_padding: Dp::new(5.0),
                row_height: Dp::new(24.0),
                separator_height: Dp::new(9.0),
                horizontal_padding: Dp::new(8.0),
                indicator_width: Dp::new(20.0),
                accelerator_gap: Dp::new(20.0),
                submenu_width: Dp::new(18.0),
                icon_size: Dp::new(13.0),
                surface_radius: Dp::new(7.0),
                row_radius: Dp::new(4.0),
                shadow_offset: Dp::new(3.0),
                shadow_alpha: 30,
                submenu_open_delay_ms: 225,
            },
        },
        #[cfg(feature = "info-bar")]
        info_bar: PlatformInfoBarProfile {
            composition: PlatformInfoBarComposition::AppKitStatus,
            metrics: ZsInfoBarMetrics {
                minimum_height: Dp::new(56.0),
                horizontal_padding: Dp::new(14.0),
                vertical_padding: Dp::new(8.0),
                content_gap: Dp::new(10.0),
                control_gap: Dp::new(6.0),
                control_height: Dp::new(28.0),
                icon_size: Dp::new(18.0),
                accent_width: Dp::new(0.0),
                surface_radius: Dp::new(8.0),
                control_radius: Dp::new(6.0),
                title_line_height: Dp::new(18.0),
                message_line_height: Dp::new(16.0),
                average_character_width: Dp::new(6.8),
            },
            surface_alpha: 18,
        },
        #[cfg(feature = "teaching-tip")]
        teaching_tip: PlatformTeachingTipProfile {
            composition: PlatformTeachingTipComposition::AppKitPopover,
            metrics: ZsTeachingTipMetrics {
                minimum_width: Dp::new(220.0),
                maximum_width: Dp::new(300.0),
                viewport_margin: Dp::new(12.0),
                horizontal_padding: Dp::new(16.0),
                vertical_padding: Dp::new(12.0),
                content_gap: Dp::new(6.0),
                control_gap: Dp::new(10.0),
                control_height: Dp::new(28.0),
                title_line_height: Dp::new(20.0),
                subtitle_height: Dp::new(36.0),
                average_character_width: Dp::new(6.8),
                surface_radius: Dp::new(10.0),
                control_radius: Dp::new(6.0),
                tail_size: Dp::new(10.0),
                target_gap: Dp::new(4.0),
            },
            shadow_alpha: 26,
        },
        #[cfg(feature = "toast")]
        toast: PlatformToastProfile {
            composition: PlatformToastComposition::AppKitForeground,
            metrics: ZsToastMetrics {
                maximum_width: Dp::new(380.0),
                viewport_margin: Dp::new(20.0),
                bottom_margin: Dp::new(20.0),
                horizontal_padding: Dp::new(14.0),
                vertical_padding: Dp::new(10.0),
                control_gap: Dp::new(6.0),
                control_height: Dp::new(28.0),
                surface_radius: Dp::new(10.0),
                control_radius: Dp::new(6.0),
                line_height: Dp::new(18.0),
                average_character_width: Dp::new(6.8),
            },
            shadow_alpha: 24,
        },
        #[cfg(feature = "breadcrumb")]
        breadcrumb: PlatformBreadcrumbProfile {
            metrics: ZsBreadcrumbMetrics {
                control_height: Dp::new(24.0),
                horizontal_padding: Dp::new(7.0),
                minimum_item_width: Dp::new(28.0),
                separator_width: Dp::new(16.0),
                icon_size: Dp::new(13.0),
                radius: Dp::new(5.0),
                character_width: Dp::new(6.6),
                label_measurement_guard: Dp::new(8.0),
                popup_row_height: Dp::new(24.0),
                popup_padding: Dp::new(4.0),
            },
            collapse_behavior: PlatformBreadcrumbCollapseBehavior::PreserveRootWhenPossible,
        },
        #[cfg(feature = "toggle-button")]
        toggle_button: PlatformToggleButtonProfile {
            metrics: ZsToggleButtonMetrics {
                minimum_height: Dp::new(28.0),
                radius: Dp::new(6.0),
                horizontal_padding: Dp::new(12.0),
                selected_indicator_width: Dp::new(14.0),
                selected_indicator_height: Dp::new(2.0),
                checked_content_offset_y: Dp::new(1.0),
            },
        },
        #[cfg(feature = "number-box")]
        number_box: PlatformNumberBoxProfile {
            metrics: ZsNumberBoxMetrics {
                button_width: Dp::new(18.0),
                button_gap: Dp::new(4.0),
                text_inset: Dp::new(7.0),
                radius: Dp::new(5.0),
                horizontal_buttons: false,
            },
            button_icon_size: Dp::new(10.0),
            stepper_presentation: PlatformNumberBoxStepperPresentation::ChevronIcons,
        },
        #[cfg(feature = "password-box")]
        password_box: PlatformPasswordBoxProfile {
            metrics: ZsPasswordBoxMetrics {
                minimum_height: Dp::new(28.0),
                radius: Dp::new(5.0),
                text_inset: Dp::new(7.0),
                reveal_width: Dp::new(28.0),
                reveal_icon_size: Dp::new(15.0),
            },
            default_reveal_mode: ZsPasswordRevealMode::Hidden,
        },
        #[cfg(feature = "tooltip")]
        tooltip: PlatformTooltipProfile {
            metrics: ZsTooltipMetrics {
                maximum_width: Dp::new(300.0),
                horizontal_padding: Dp::new(7.0),
                vertical_padding: Dp::new(5.0),
                gap: Dp::new(6.0),
                radius: Dp::new(5.0),
                line_height: Dp::new(15.0),
                average_character_width: Dp::new(6.2),
            },
        },
        #[cfg(feature = "progress-ring")]
        progress_ring: PlatformProgressRingProfile {
            small: PlatformProgressRingSizeProfile {
                diameter: Dp::new(16.0),
                stroke_width: Dp::new(2.0),
            },
            medium: PlatformProgressRingSizeProfile {
                diameter: Dp::new(20.0),
                stroke_width: Dp::new(2.0),
            },
            large: PlatformProgressRingSizeProfile {
                diameter: Dp::new(32.0),
                stroke_width: Dp::new(3.0),
            },
            indeterminate_sweep_degrees: 90,
            revolution_ms: 900,
            indicator_role: ColorRole::PrimaryText,
            track_role: ColorRole::Control,
        },
        #[cfg(feature = "auto-suggest")]
        auto_suggest: PlatformAutoSuggestProfile {
            metrics: ZsAutoSuggestMetrics {
                control_height: Dp::new(28.0),
                row_height: Dp::new(28.0),
                text_padding: Dp::new(8.0),
                icon_column_width: Dp::new(24.0),
                icon_size: Dp::new(14.0),
                popup_gap: Dp::new(6.0),
                control_radius: Dp::new(6.0),
                overlay_radius: Dp::new(10.0),
                leading_search_icon: true,
            },
        },
        #[cfg(feature = "grid-view")]
        grid_view: PlatformGridViewProfile {
            metrics: ZsGridViewMetrics {
                minimum_item_width: Dp::new(124.0),
                item_height: Dp::new(104.0),
                item_gap: Dp::new(10.0),
                item_padding: Dp::new(9.0),
                media_height: Dp::new(54.0),
                icon_size: Dp::new(28.0),
                item_radius: Dp::new(8.0),
                media_radius: Dp::new(6.0),
                text_gap: Dp::new(1.0),
            },
            selection: PlatformCollectionSelectionProfile {
                fill_role: ColorRole::Accent,
                fill_alpha: None,
                foreground: ColorRole::AccentText,
            },
        },
        #[cfg(feature = "tree")]
        tree_view: PlatformTreeViewProfile {
            metrics: ZsTreeViewMetrics {
                row_height: Dp::new(22.0),
                depth_indent: Dp::new(16.0),
                disclosure_column: Dp::new(18.0),
                disclosure_size: Dp::new(10.0),
                icon_size: Dp::new(16.0),
                leading_padding: Dp::new(4.0),
                content_gap: Dp::new(4.0),
                row_radius: Dp::new(4.0),
            },
            selection: PlatformCollectionSelectionProfile {
                fill_role: ColorRole::Accent,
                fill_alpha: None,
                foreground: ColorRole::AccentText,
            },
        },
        #[cfg(feature = "table")]
        table: PlatformTableProfile {
            metrics: ZsTableMetrics {
                header_height: Dp::new(24.0),
                row_height: Dp::new(24.0),
                horizontal_padding: Dp::new(8.0),
                sort_icon_size: Dp::new(10.0),
                radius: Dp::new(5.0),
                separator_width: Dp::new(1.0),
            },
            selection: PlatformCollectionSelectionProfile {
                fill_role: ColorRole::Accent,
                fill_alpha: None,
                foreground: ColorRole::AccentText,
            },
        },
        #[cfg(feature = "time-picker")]
        time_picker: PlatformTimePickerProfile {
            metrics: ZsTimePickerMetrics {
                popup_width: Dp::new(216.0),
                row_height: Dp::new(30.0),
                visible_rows: 3,
                text_padding: Dp::new(10.0),
                icon_column_width: Dp::new(26.0),
                popup_gap: Dp::new(6.0),
                control_radius: Dp::new(6.0),
                overlay_radius: Dp::new(10.0),
            },
            default_clock: ZsClockFormat::TwentyFourHour,
            header_fill: ColorRole::Surface,
            selection: PlatformCollectionSelectionProfile {
                fill_role: ColorRole::Accent,
                fill_alpha: None,
                foreground: ColorRole::AccentText,
            },
        },
        #[cfg(feature = "color-picker")]
        color_picker: PlatformColorPickerProfile {
            metrics: ZsColorPickerMetrics {
                popup_width: Dp::new(264.0),
                popup_padding: Dp::new(12.0),
                preview_size: Dp::new(40.0),
                preview_gap: Dp::new(10.0),
                spectrum_height: Dp::new(0.0),
                spectrum_gap: Dp::new(0.0),
                hue_track_height: Dp::new(0.0),
                row_height: Dp::new(32.0),
                row_gap: Dp::new(3.0),
                label_width: Dp::new(20.0),
                value_width: Dp::new(36.0),
                track_height: Dp::new(6.0),
                thumb_width: Dp::new(10.0),
                popup_gap: Dp::new(6.0),
                control_radius: Dp::new(6.0),
                overlay_radius: Dp::new(10.0),
            },
            swatch_size: Dp::new(18.0),
            header_fill: ColorRole::Surface,
            active_channel_alpha: 18,
        },
        #[cfg(feature = "command-palette")]
        command_palette: PlatformCommandPaletteProfile {
            metrics: ZsCommandPaletteMetrics {
                preferred_width: Dp::new(560.0),
                viewport_margin: Dp::new(24.0),
                top_offset: Dp::new(64.0),
                search_height: Dp::new(48.0),
                row_height: Dp::new(44.0),
                horizontal_padding: Dp::new(12.0),
                icon_size: Dp::new(18.0),
                icon_column_width: Dp::new(32.0),
                shortcut_width: Dp::new(96.0),
                surface_radius: Dp::new(14.0),
                search_radius: Dp::new(8.0),
                row_radius: Dp::new(7.0),
            },
            scrim_alpha: 44,
        },
        #[cfg(feature = "document-shell")]
        document_shell: PlatformDocumentShellProfile {
            tab_strip_height: Dp::new(32.0),
            command_bar_height: Dp::new(28.0),
            status_bar_height: Dp::new(24.0),
            surface_margin: Dp::new(12.0),
            editor_inset: Dp::new(8.0),
            editor_vertical_gap: Dp::new(6.0),
            compact_threshold: Dp::new(760.0),
            regular_tab_width: Dp::new(160.0),
            compact_tab_width: Dp::new(140.0),
            minimum_tab_width: Dp::new(72.0),
            reserved_tab_action_width: Dp::new(28.0),
            tab_top_inset: Dp::new(0.0),
            tab_height: Dp::new(32.0),
            tab_action_size: Dp::new(22.0),
            tab_action_inset: Dp::new(5.0),
            tab_action_gap: Dp::new(6.0),
            tab_radius: Dp::new(6.0),
            tab_icon_leading: Dp::new(10.0),
            tab_icon_size: Dp::new(14.0),
            tab_label_leading: Dp::new(30.0),
            clean_title_reserve: Dp::new(34.0),
            dirty_title_reserve: Dp::new(42.0),
            dirty_indicator_size: Dp::new(5.0),
            dirty_indicator_gap: Dp::new(8.0),
            command_height: Dp::new(28.0),
            command_gap: Dp::new(6.0),
            command_group_gap: Dp::new(12.0),
            command_radius: Dp::new(6.0),
            command_icon_size: Dp::new(16.0),
            command_icon_leading: Dp::new(8.0),
            command_label_gap: Dp::new(6.0),
            command_label_trailing: Dp::new(10.0),
            separator_vertical_inset: Dp::new(6.0),
            editor_radius: Dp::new(6.0),
            status_horizontal_inset: Dp::new(12.0),
        },
        #[cfg(feature = "calculator")]
        calculator_shell: PlatformCalculatorShellProfile {
            header_height: Dp::new(40.0),
            display_block_height: Dp::new(104.0),
            memory_row_height: Dp::new(28.0),
            surface_margin: Dp::new(8.0),
            button_gap: Dp::new(6.0),
            expression_top_gap: Dp::new(6.0),
            expression_height: Dp::new(20.0),
            display_bottom_gap: Dp::new(6.0),
            memory_indicator_width: Dp::new(16.0),
            header_action_size: Dp::new(28.0),
            header_icon_leading: Dp::new(8.0),
            header_icon_size: Dp::new(16.0),
            header_title_leading: Dp::new(32.0),
            header_title_trailing_reserve: Dp::new(68.0),
            history_clear_width: Dp::new(82.0),
            history_clear_height: Dp::new(28.0),
            history_clear_top_inset: Dp::new(8.0),
            history_clear_trailing_inset: Dp::new(8.0),
            history_radius: Dp::new(10.0),
            history_horizontal_inset: Dp::new(14.0),
            history_title_top_inset: Dp::new(6.0),
            history_title_height: Dp::new(28.0),
            history_title_trailing_reserve: Dp::new(106.0),
            history_empty_top_inset: Dp::new(56.0),
            history_empty_height: Dp::new(22.0),
            history_entries_top_inset: Dp::new(46.0),
            history_expression_height: Dp::new(18.0),
            history_result_height: Dp::new(24.0),
            history_entry_gap: Dp::new(10.0),
            button_radius: Dp::new(6.0),
            button_icon_size: Dp::new(16.0),
            number_fill: ColorRole::Control,
            function_fill: ColorRole::Control,
            operator_fill: ColorRole::Control,
            draw_neutral_button_border: false,
            title_weight: TextWeight::Regular,
            display_weight: TextWeight::Regular,
            accent_weight: TextWeight::Semibold,
        },
        shell: PlatformShellProfile {
            style: ZsPlatformStyle::Macos,
            navigation: PlatformShellNavigationComposition::AppKitSourceList,
            sections: PlatformShellSectionComposition::AppKitForms,
            preferred_navigation_width: Dp::new(240.0),
            top_height: Dp::new(64.0),
            navigation_start: Dp::new(52.0),
            content_gap: Dp::new(24.0),
            content_top_gap: Dp::new(12.0),
            viewport_mask_height: Dp::new(8.0),
            scrollbar_width: Dp::new(2.0),
            active_scrollbar_width: Dp::new(4.0),
            scrollbar_margin: Dp::new(4.0),
            section_header_height: Dp::new(28.0),
            section_row_height: Dp::new(36.0),
            section_row_gap: Dp::new(8.0),
            section_gap: Dp::new(16.0),
            section_horizontal_padding: Dp::new(0.0),
            section_height_extra: Dp::new(12.0),
            section_body_bottom_inset: Dp::new(0.0),
            navigation_item_height: Dp::new(28.0),
            navigation_item_stride: Dp::new(32.0),
            navigation_item_inset: Dp::new(8.0),
            navigation_item_radius: Dp::new(6.0),
            section_radius: Dp::new(0.0),
            title_x: Dp::new(24.0),
            title_y: Dp::new(20.0),
            title_width: Dp::new(360.0),
            title_height: Dp::new(28.0),
            menu_icon_x: Dp::new(0.0),
            menu_icon_y: Dp::new(0.0),
            menu_icon_size: Dp::new(0.0),
            show_menu_icon: false,
            app_title_x: Dp::new(16.0),
            app_title_y: Dp::new(16.0),
            app_title_width: Dp::new(208.0),
            app_title_height: Dp::new(24.0),
            action_margin: Dp::new(20.0),
            action_height: Dp::new(28.0),
            primary_action_width: Dp::new(72.0),
            secondary_action_width: Dp::new(64.0),
            action_gap: Dp::new(8.0),
            draw_row_separators: false,
        },
    }
}
