use super::*;

pub(super) const fn profile() -> PlatformComponentProfile {
    PlatformComponentProfile {
        style: ZsPlatformStyle::Macos,
        #[cfg(feature = "label")]
        section: PlatformSectionProfile {
            composition: PlatformSectionComposition::AppKitForm,
            heading_color: ColorRole::SecondaryText,
        },
        #[cfg(feature = "label")]
        navigation: PlatformNavigationProfile {
            composition: PlatformNavigationComposition::AppKitSourceList,
            behavior: PlatformNavigationBehavior::AppKitSplitView,
            title_role: TextRole::Body,
            preferred_pane_width: Dp::new(240.0),
            horizontal_inset: Dp::new(24.0),
            pane_color: ColorRole::SurfaceRaised,
            scrim_alpha: 32,
            toggle_icon_size: Dp::new(16.0),
        },
        #[cfg(feature = "button")]
        button: PlatformButtonProfile {
            fill: ColorRole::Control,
            stroke: None,
        },
        #[cfg(feature = "button")]
        command_bar: PlatformCommandBarProfile {
            bar_height: Dp::new(28.0),
            button_height: Dp::new(28.0),
            icon_size: Dp::new(16.0),
            content_gap: Dp::new(6.0),
            item_gap: Dp::new(6.0),
            label_role: TextRole::Button,
        },
        #[cfg(feature = "tabs")]
        tabs: PlatformTabProfile {
            composition: PlatformTabComposition::AppKitSegmented,
            metrics: ZsTabViewMetrics {
                strip_height: Dp::new(32.0),
                header_top_padding: Dp::new(0.0),
                item_height: Dp::new(32.0),
                outer_inset: Dp::new(12.0),
                item_gap: Dp::new(0.0),
                horizontal_padding: Dp::new(14.0),
                icon_size: Dp::new(14.0),
                icon_gap: Dp::new(6.0),
                minimum_item_width: Dp::new(72.0),
                maximum_item_width: Dp::new(160.0),
                radius: Dp::new(6.0),
                selection_indicator_height: Dp::new(0.0),
            },
            label_role: TextRole::Button,
            arrow_selects: true,
            supports_home_end_focus: false,
            cycle_shortcut: PlatformTabCycleShortcut::None,
        },
        #[cfg(feature = "dialog")]
        dialog: PlatformDialogProfile {
            composition: PlatformDialogComposition::AppKitTrailingActions,
            metrics: ZsContentDialogMetrics {
                minimum_width: Dp::new(360.0),
                maximum_width: Dp::new(480.0),
                viewport_margin: Dp::new(28.0),
                content_padding: Dp::new(20.0),
                title_gap: Dp::new(8.0),
                action_gap: Dp::new(20.0),
                button_gap: Dp::new(8.0),
                button_height: Dp::new(28.0),
                minimum_button_width: Dp::new(82.0),
                surface_radius: Dp::new(12.0),
                button_radius: Dp::new(6.0),
            },
            scrim_alpha: 56,
            estimated_glyph_width: Dp::new(7.0),
            estimated_label_padding: Dp::new(28.0),
        },
        shell: PlatformShellProfile {
            style: ZsPlatformStyle::Macos,
            navigation: PlatformShellNavigationComposition::AppKitSourceList,
            sections: PlatformShellSectionComposition::AppKitForms,
            preferred_navigation_width: Dp::new(240.0),
            top_height: Dp::new(64.0),
            navigation_start: Dp::new(52.0),
            content_gap: Dp::new(24.0),
            content_top_gap: Dp::new(12.0),
            viewport_mask_height: Dp::new(8.0),
            scrollbar_width: Dp::new(2.0),
            active_scrollbar_width: Dp::new(4.0),
            scrollbar_margin: Dp::new(4.0),
            section_header_height: Dp::new(28.0),
            section_row_height: Dp::new(36.0),
            section_row_gap: Dp::new(8.0),
            section_gap: Dp::new(16.0),
            section_horizontal_padding: Dp::new(0.0),
            section_height_extra: Dp::new(12.0),
            section_body_bottom_inset: Dp::new(0.0),
            navigation_item_height: Dp::new(28.0),
            navigation_item_stride: Dp::new(32.0),
            navigation_item_inset: Dp::new(8.0),
            navigation_item_radius: Dp::new(6.0),
            section_radius: Dp::new(0.0),
            title_x: Dp::new(24.0),
            title_y: Dp::new(20.0),
            title_width: Dp::new(360.0),
            title_height: Dp::new(28.0),
            menu_icon_x: Dp::new(0.0),
            menu_icon_y: Dp::new(0.0),
            menu_icon_size: Dp::new(0.0),
            show_menu_icon: false,
            app_title_x: Dp::new(16.0),
            app_title_y: Dp::new(16.0),
            app_title_width: Dp::new(208.0),
            app_title_height: Dp::new(24.0),
            action_margin: Dp::new(20.0),
            action_height: Dp::new(28.0),
            primary_action_width: Dp::new(72.0),
            secondary_action_width: Dp::new(64.0),
            action_gap: Dp::new(8.0),
            draw_row_separators: false,
        },
    }
}
