use super::*;

pub(super) const fn profile() -> PlatformComponentProfile {
    PlatformComponentProfile {
        style: ZsPlatformStyle::Macos,
        base_control: PlatformBaseControlProfile {
            metrics: ZsBaseControlMetrics {
                body_line_height: Dp::new(16.0),
                average_character_width: Dp::new(6.8),
                button_minimum_width: Dp::new(82.0),
                button_height: Dp::new(28.0),
                button_radius: Dp::new(6.0),
                button_padding_left: Dp::new(12.0),
                button_padding_top: Dp::new(4.0),
                button_padding_right: Dp::new(12.0),
                button_padding_bottom: Dp::new(4.0),
                text_input_minimum_width: Dp::new(72.0),
                text_input_height: Dp::new(28.0),
                text_input_radius: Dp::new(5.0),
                text_input_padding_left: Dp::new(7.0),
                text_input_padding_top: Dp::new(4.0),
                text_input_padding_right: Dp::new(7.0),
                text_input_padding_bottom: Dp::new(4.0),
                check_minimum_width: Dp::new(82.0),
                check_height: Dp::new(22.0),
                check_indicator_size: Dp::new(14.0),
                toggle_width: Dp::new(42.0),
                toggle_height: Dp::new(28.0),
                toggle_track_width: Dp::new(36.0),
                toggle_track_height: Dp::new(20.0),
                toggle_knob_off_size: Dp::new(16.0),
                toggle_knob_on_size: Dp::new(16.0),
                slider_minimum_width: Dp::new(96.0),
                slider_height: Dp::new(28.0),
                slider_track_height: Dp::new(3.0),
                slider_thumb_size: Dp::new(14.0),
                radio_minimum_width: Dp::new(82.0),
                radio_height: Dp::new(22.0),
                radio_indicator_size: Dp::new(16.0),
                radio_dot_size: Dp::new(6.0),
                progress_slot_height: Dp::new(12.0),
                progress_track_height: Dp::new(3.0),
                selection_minimum_width: Dp::new(96.0),
                selection_height: Dp::new(28.0),
                time_picker_minimum_width: Dp::new(120.0),
            },
        },
        #[cfg(feature = "label")]
        section: PlatformSectionProfile {
            composition: PlatformSectionComposition::AppKitForm,
            heading_color: ColorRole::SecondaryText,
        },
        #[cfg(feature = "label")]
        navigation: PlatformNavigationProfile {
            composition: PlatformNavigationComposition::AppKitSourceList,
            behavior: PlatformNavigationBehavior::AppKitSplitView,
            title_role: TextRole::Body,
            preferred_pane_width: Dp::new(240.0),
            horizontal_inset: Dp::new(24.0),
            pane_color: ColorRole::SurfaceRaised,
            scrim_alpha: 32,
            toggle_icon_size: Dp::new(16.0),
        },
        #[cfg(feature = "button")]
        button: PlatformButtonProfile {
            fill: ColorRole::Control,
            stroke: None,
            navigation_item: PlatformNavigationItemProfile {
                composition: PlatformNavigationItemComposition::AppKitSourceListRow,
                metrics: ZsNavigationItemMetrics {
                    open_pane_width: Dp::new(240.0),
                    item_height: Dp::new(28.0),
                    icon_size: Dp::new(16.0),
                    icon_box_width: Dp::new(28.0),
                    text_leading_margin: Dp::new(4.0),
                    trailing_padding: Dp::new(8.0),
                    indicator_width: Dp::new(0.0),
                    indicator_height: Dp::new(0.0),
                    indicator_radius: Dp::new(0.0),
                    radius: Dp::new(6.0),
                },
            },
        },
        #[cfg(feature = "button")]
        command_bar: PlatformCommandBarProfile {
            bar_height: Dp::new(28.0),
            button_height: Dp::new(28.0),
            icon_size: Dp::new(16.0),
            content_gap: Dp::new(6.0),
            item_gap: Dp::new(6.0),
            label_role: TextRole::Button,
        },
        #[cfg(feature = "tabs")]
        tabs: PlatformTabProfile {
            composition: PlatformTabComposition::AppKitSegmented,
            metrics: ZsTabViewMetrics {
                strip_height: Dp::new(32.0),
                header_top_padding: Dp::new(0.0),
                item_height: Dp::new(32.0),
                outer_inset: Dp::new(12.0),
                item_gap: Dp::new(0.0),
                horizontal_padding: Dp::new(14.0),
                icon_size: Dp::new(14.0),
                icon_gap: Dp::new(6.0),
                minimum_item_width: Dp::new(72.0),
                maximum_item_width: Dp::new(160.0),
                radius: Dp::new(6.0),
                selection_indicator_height: Dp::new(0.0),
            },
            label_role: TextRole::Button,
            arrow_selects: true,
            supports_home_end_focus: false,
            cycle_shortcut: PlatformTabCycleShortcut::None,
        },
        #[cfg(feature = "dialog")]
        dialog: PlatformDialogProfile {
            composition: PlatformDialogComposition::AppKitTrailingActions,
            metrics: ZsContentDialogMetrics {
                minimum_width: Dp::new(360.0),
                maximum_width: Dp::new(480.0),
                viewport_margin: Dp::new(28.0),
                content_padding: Dp::new(20.0),
                title_gap: Dp::new(8.0),
                action_gap: Dp::new(20.0),
                button_gap: Dp::new(8.0),
                button_height: Dp::new(28.0),
                minimum_button_width: Dp::new(82.0),
                surface_radius: Dp::new(12.0),
                button_radius: Dp::new(6.0),
            },
            scrim_alpha: 56,
            estimated_glyph_width: Dp::new(7.0),
            estimated_label_padding: Dp::new(28.0),
        },
        #[cfg(feature = "info-bar")]
        info_bar: PlatformInfoBarProfile {
            composition: PlatformInfoBarComposition::AppKitStatus,
            metrics: ZsInfoBarMetrics {
                minimum_height: Dp::new(56.0),
                horizontal_padding: Dp::new(14.0),
                vertical_padding: Dp::new(8.0),
                content_gap: Dp::new(10.0),
                control_gap: Dp::new(6.0),
                control_height: Dp::new(28.0),
                icon_size: Dp::new(18.0),
                accent_width: Dp::new(0.0),
                surface_radius: Dp::new(8.0),
                control_radius: Dp::new(6.0),
                title_line_height: Dp::new(18.0),
                message_line_height: Dp::new(16.0),
                average_character_width: Dp::new(6.8),
            },
            surface_alpha: 18,
        },
        #[cfg(feature = "teaching-tip")]
        teaching_tip: PlatformTeachingTipProfile {
            composition: PlatformTeachingTipComposition::AppKitPopover,
            metrics: ZsTeachingTipMetrics {
                minimum_width: Dp::new(220.0),
                maximum_width: Dp::new(300.0),
                viewport_margin: Dp::new(12.0),
                horizontal_padding: Dp::new(16.0),
                vertical_padding: Dp::new(12.0),
                content_gap: Dp::new(6.0),
                control_gap: Dp::new(10.0),
                control_height: Dp::new(28.0),
                title_line_height: Dp::new(20.0),
                subtitle_height: Dp::new(36.0),
                average_character_width: Dp::new(6.8),
                surface_radius: Dp::new(10.0),
                control_radius: Dp::new(6.0),
                tail_size: Dp::new(10.0),
                target_gap: Dp::new(4.0),
            },
            shadow_alpha: 26,
        },
        #[cfg(feature = "toast")]
        toast: PlatformToastProfile {
            composition: PlatformToastComposition::AppKitForeground,
            metrics: ZsToastMetrics {
                maximum_width: Dp::new(380.0),
                viewport_margin: Dp::new(20.0),
                bottom_margin: Dp::new(20.0),
                horizontal_padding: Dp::new(14.0),
                vertical_padding: Dp::new(10.0),
                control_gap: Dp::new(6.0),
                control_height: Dp::new(28.0),
                surface_radius: Dp::new(10.0),
                control_radius: Dp::new(6.0),
                line_height: Dp::new(18.0),
                average_character_width: Dp::new(6.8),
            },
            shadow_alpha: 24,
        },
        #[cfg(feature = "breadcrumb")]
        breadcrumb: PlatformBreadcrumbProfile {
            metrics: ZsBreadcrumbMetrics {
                control_height: Dp::new(24.0),
                horizontal_padding: Dp::new(7.0),
                minimum_item_width: Dp::new(28.0),
                separator_width: Dp::new(16.0),
                icon_size: Dp::new(13.0),
                radius: Dp::new(5.0),
                character_width: Dp::new(6.6),
                label_measurement_guard: Dp::new(8.0),
                popup_row_height: Dp::new(24.0),
                popup_padding: Dp::new(4.0),
            },
            collapse_behavior: PlatformBreadcrumbCollapseBehavior::PreserveRootWhenPossible,
        },
        #[cfg(feature = "toggle-button")]
        toggle_button: PlatformToggleButtonProfile {
            metrics: ZsToggleButtonMetrics {
                minimum_height: Dp::new(28.0),
                radius: Dp::new(6.0),
                horizontal_padding: Dp::new(12.0),
                selected_indicator_width: Dp::new(14.0),
                selected_indicator_height: Dp::new(2.0),
                checked_content_offset_y: Dp::new(1.0),
            },
        },
        #[cfg(feature = "number-box")]
        number_box: PlatformNumberBoxProfile {
            metrics: ZsNumberBoxMetrics {
                button_width: Dp::new(18.0),
                button_gap: Dp::new(4.0),
                text_inset: Dp::new(7.0),
                radius: Dp::new(5.0),
                horizontal_buttons: false,
            },
            button_icon_size: Dp::new(10.0),
            stepper_presentation: PlatformNumberBoxStepperPresentation::ChevronIcons,
        },
        #[cfg(feature = "auto-suggest")]
        auto_suggest: PlatformAutoSuggestProfile {
            metrics: ZsAutoSuggestMetrics {
                control_height: Dp::new(28.0),
                row_height: Dp::new(28.0),
                text_padding: Dp::new(8.0),
                icon_column_width: Dp::new(24.0),
                icon_size: Dp::new(14.0),
                popup_gap: Dp::new(6.0),
                control_radius: Dp::new(6.0),
                overlay_radius: Dp::new(10.0),
                leading_search_icon: true,
            },
        },
        #[cfg(feature = "grid-view")]
        grid_view: PlatformGridViewProfile {
            metrics: ZsGridViewMetrics {
                minimum_item_width: Dp::new(124.0),
                item_height: Dp::new(104.0),
                item_gap: Dp::new(10.0),
                item_padding: Dp::new(9.0),
                media_height: Dp::new(54.0),
                icon_size: Dp::new(28.0),
                item_radius: Dp::new(8.0),
                media_radius: Dp::new(6.0),
                text_gap: Dp::new(1.0),
            },
            selection: PlatformCollectionSelectionProfile {
                fill_role: ColorRole::Accent,
                fill_alpha: None,
                foreground: ColorRole::AccentText,
            },
        },
        #[cfg(feature = "tree")]
        tree_view: PlatformTreeViewProfile {
            metrics: ZsTreeViewMetrics {
                row_height: Dp::new(22.0),
                depth_indent: Dp::new(16.0),
                disclosure_column: Dp::new(18.0),
                disclosure_size: Dp::new(10.0),
                icon_size: Dp::new(16.0),
                leading_padding: Dp::new(4.0),
                content_gap: Dp::new(4.0),
                row_radius: Dp::new(4.0),
            },
            selection: PlatformCollectionSelectionProfile {
                fill_role: ColorRole::Accent,
                fill_alpha: None,
                foreground: ColorRole::AccentText,
            },
        },
        #[cfg(feature = "table")]
        table: PlatformTableProfile {
            metrics: ZsTableMetrics {
                header_height: Dp::new(24.0),
                row_height: Dp::new(24.0),
                horizontal_padding: Dp::new(8.0),
                sort_icon_size: Dp::new(10.0),
                radius: Dp::new(5.0),
                separator_width: Dp::new(1.0),
            },
            selection: PlatformCollectionSelectionProfile {
                fill_role: ColorRole::Accent,
                fill_alpha: None,
                foreground: ColorRole::AccentText,
            },
        },
        #[cfg(feature = "time-picker")]
        time_picker: PlatformTimePickerProfile {
            metrics: ZsTimePickerMetrics {
                popup_width: Dp::new(216.0),
                row_height: Dp::new(30.0),
                visible_rows: 3,
                text_padding: Dp::new(10.0),
                icon_column_width: Dp::new(26.0),
                popup_gap: Dp::new(6.0),
                control_radius: Dp::new(6.0),
                overlay_radius: Dp::new(10.0),
            },
            header_fill: ColorRole::Surface,
            selection: PlatformCollectionSelectionProfile {
                fill_role: ColorRole::Accent,
                fill_alpha: None,
                foreground: ColorRole::AccentText,
            },
        },
        #[cfg(feature = "color-picker")]
        color_picker: PlatformColorPickerProfile {
            metrics: ZsColorPickerMetrics {
                popup_width: Dp::new(264.0),
                popup_padding: Dp::new(12.0),
                preview_size: Dp::new(40.0),
                preview_gap: Dp::new(10.0),
                spectrum_height: Dp::new(0.0),
                spectrum_gap: Dp::new(0.0),
                hue_track_height: Dp::new(0.0),
                row_height: Dp::new(32.0),
                row_gap: Dp::new(3.0),
                label_width: Dp::new(20.0),
                value_width: Dp::new(36.0),
                track_height: Dp::new(6.0),
                thumb_width: Dp::new(10.0),
                popup_gap: Dp::new(6.0),
                control_radius: Dp::new(6.0),
                overlay_radius: Dp::new(10.0),
            },
            swatch_size: Dp::new(18.0),
            header_fill: ColorRole::Surface,
            active_channel_alpha: 18,
        },
        #[cfg(feature = "command-palette")]
        command_palette: PlatformCommandPaletteProfile {
            metrics: ZsCommandPaletteMetrics {
                preferred_width: Dp::new(560.0),
                viewport_margin: Dp::new(24.0),
                top_offset: Dp::new(64.0),
                search_height: Dp::new(48.0),
                row_height: Dp::new(44.0),
                horizontal_padding: Dp::new(12.0),
                icon_size: Dp::new(18.0),
                icon_column_width: Dp::new(32.0),
                shortcut_width: Dp::new(96.0),
                surface_radius: Dp::new(14.0),
                search_radius: Dp::new(8.0),
                row_radius: Dp::new(7.0),
            },
            scrim_alpha: 44,
        },
        shell: PlatformShellProfile {
            style: ZsPlatformStyle::Macos,
            navigation: PlatformShellNavigationComposition::AppKitSourceList,
            sections: PlatformShellSectionComposition::AppKitForms,
            preferred_navigation_width: Dp::new(240.0),
            top_height: Dp::new(64.0),
            navigation_start: Dp::new(52.0),
            content_gap: Dp::new(24.0),
            content_top_gap: Dp::new(12.0),
            viewport_mask_height: Dp::new(8.0),
            scrollbar_width: Dp::new(2.0),
            active_scrollbar_width: Dp::new(4.0),
            scrollbar_margin: Dp::new(4.0),
            section_header_height: Dp::new(28.0),
            section_row_height: Dp::new(36.0),
            section_row_gap: Dp::new(8.0),
            section_gap: Dp::new(16.0),
            section_horizontal_padding: Dp::new(0.0),
            section_height_extra: Dp::new(12.0),
            section_body_bottom_inset: Dp::new(0.0),
            navigation_item_height: Dp::new(28.0),
            navigation_item_stride: Dp::new(32.0),
            navigation_item_inset: Dp::new(8.0),
            navigation_item_radius: Dp::new(6.0),
            section_radius: Dp::new(0.0),
            title_x: Dp::new(24.0),
            title_y: Dp::new(20.0),
            title_width: Dp::new(360.0),
            title_height: Dp::new(28.0),
            menu_icon_x: Dp::new(0.0),
            menu_icon_y: Dp::new(0.0),
            menu_icon_size: Dp::new(0.0),
            show_menu_icon: false,
            app_title_x: Dp::new(16.0),
            app_title_y: Dp::new(16.0),
            app_title_width: Dp::new(208.0),
            app_title_height: Dp::new(24.0),
            action_margin: Dp::new(20.0),
            action_height: Dp::new(28.0),
            primary_action_width: Dp::new(72.0),
            secondary_action_width: Dp::new(64.0),
            action_gap: Dp::new(8.0),
            draw_row_separators: false,
        },
    }
}
