use super::*;

pub(super) const fn profile() -> PlatformComponentProfile {
    PlatformComponentProfile {
        style: ZsPlatformStyle::Windows,
        #[cfg(feature = "label")]
        section: PlatformSectionProfile {
            composition: PlatformSectionComposition::FluentCard,
            heading_color: ColorRole::PrimaryText,
        },
        #[cfg(feature = "label")]
        navigation: PlatformNavigationProfile {
            composition: PlatformNavigationComposition::FluentPane,
            behavior: PlatformNavigationBehavior::FluentAdaptive,
            title_role: TextRole::Subtitle,
            preferred_pane_width: Dp::new(320.0),
            horizontal_inset: Dp::new(32.0),
            pane_color: ColorRole::SurfaceRaised,
            scrim_alpha: 42,
            toggle_icon_size: Dp::new(20.0),
        },
        #[cfg(feature = "button")]
        button: PlatformButtonProfile {
            fill: ColorRole::Control,
            stroke: Some(ColorRole::Border),
        },
        #[cfg(feature = "button")]
        command_bar: PlatformCommandBarProfile {
            bar_height: Dp::new(48.0),
            button_height: Dp::new(48.0),
            icon_size: Dp::new(20.0),
            content_gap: Dp::new(8.0),
            item_gap: Dp::new(8.0),
            label_role: TextRole::Caption,
        },
        #[cfg(feature = "tabs")]
        tabs: PlatformTabProfile {
            composition: PlatformTabComposition::FluentUnderline,
            metrics: ZsTabViewMetrics {
                strip_height: Dp::new(40.0),
                header_top_padding: Dp::new(8.0),
                item_height: Dp::new(32.0),
                outer_inset: Dp::new(0.0),
                item_gap: Dp::new(0.0),
                horizontal_padding: Dp::new(8.0),
                icon_size: Dp::new(16.0),
                icon_gap: Dp::new(10.0),
                minimum_item_width: Dp::new(100.0),
                maximum_item_width: Dp::new(240.0),
                radius: Dp::new(8.0),
                selection_indicator_height: Dp::new(2.0),
            },
            label_role: TextRole::Body,
            arrow_selects: false,
            supports_home_end_focus: false,
            cycle_shortcut: PlatformTabCycleShortcut::ControlTab,
        },
        #[cfg(feature = "dialog")]
        dialog: PlatformDialogProfile {
            composition: PlatformDialogComposition::FluentEqualActions,
            metrics: ZsContentDialogMetrics {
                minimum_width: Dp::new(320.0),
                maximum_width: Dp::new(548.0),
                viewport_margin: Dp::new(24.0),
                content_padding: Dp::new(24.0),
                title_gap: Dp::new(12.0),
                action_gap: Dp::new(24.0),
                button_gap: Dp::new(8.0),
                button_height: Dp::new(40.0),
                minimum_button_width: Dp::new(88.0),
                surface_radius: Dp::new(8.0),
                button_radius: Dp::new(4.0),
            },
            scrim_alpha: 88,
            estimated_glyph_width: Dp::new(0.0),
            estimated_label_padding: Dp::new(0.0),
        },
        #[cfg(feature = "info-bar")]
        info_bar: PlatformInfoBarProfile {
            composition: PlatformInfoBarComposition::FluentStatus,
            metrics: ZsInfoBarMetrics {
                minimum_height: Dp::new(48.0),
                horizontal_padding: Dp::new(16.0),
                vertical_padding: Dp::new(10.0),
                content_gap: Dp::new(12.0),
                control_gap: Dp::new(8.0),
                control_height: Dp::new(32.0),
                icon_size: Dp::new(20.0),
                accent_width: Dp::new(4.0),
                surface_radius: Dp::new(4.0),
                control_radius: Dp::new(4.0),
                title_line_height: Dp::new(20.0),
                message_line_height: Dp::new(18.0),
                average_character_width: Dp::new(7.2),
            },
            surface_alpha: 24,
        },
        #[cfg(feature = "teaching-tip")]
        teaching_tip: PlatformTeachingTipProfile {
            composition: PlatformTeachingTipComposition::FluentTeachingTip,
            metrics: ZsTeachingTipMetrics {
                minimum_width: Dp::new(240.0),
                maximum_width: Dp::new(320.0),
                viewport_margin: Dp::new(12.0),
                horizontal_padding: Dp::new(16.0),
                vertical_padding: Dp::new(14.0),
                content_gap: Dp::new(8.0),
                control_gap: Dp::new(12.0),
                control_height: Dp::new(32.0),
                title_line_height: Dp::new(22.0),
                subtitle_height: Dp::new(40.0),
                average_character_width: Dp::new(7.2),
                surface_radius: Dp::new(8.0),
                control_radius: Dp::new(4.0),
                tail_size: Dp::new(12.0),
                target_gap: Dp::new(4.0),
            },
            shadow_alpha: 32,
        },
        #[cfg(feature = "toast")]
        toast: PlatformToastProfile {
            composition: PlatformToastComposition::FluentForeground,
            metrics: ZsToastMetrics {
                maximum_width: Dp::new(420.0),
                viewport_margin: Dp::new(24.0),
                bottom_margin: Dp::new(24.0),
                horizontal_padding: Dp::new(16.0),
                vertical_padding: Dp::new(12.0),
                control_gap: Dp::new(8.0),
                control_height: Dp::new(32.0),
                surface_radius: Dp::new(8.0),
                control_radius: Dp::new(4.0),
                line_height: Dp::new(20.0),
                average_character_width: Dp::new(7.2),
            },
            shadow_alpha: 30,
        },
        shell: PlatformShellProfile {
            style: ZsPlatformStyle::Windows,
            navigation: PlatformShellNavigationComposition::FluentPane,
            sections: PlatformShellSectionComposition::FluentCards,
            preferred_navigation_width: Dp::new(236.0),
            top_height: Dp::new(84.0),
            navigation_start: Dp::new(80.0),
            content_gap: Dp::new(28.0),
            content_top_gap: Dp::new(16.0),
            viewport_mask_height: Dp::new(14.0),
            scrollbar_width: Dp::new(3.0),
            active_scrollbar_width: Dp::new(5.0),
            scrollbar_margin: Dp::new(3.0),
            section_header_height: Dp::new(52.0),
            section_row_height: Dp::new(32.0),
            section_row_gap: Dp::new(8.0),
            section_gap: Dp::new(12.0),
            section_horizontal_padding: Dp::new(18.0),
            section_height_extra: Dp::new(42.0),
            section_body_bottom_inset: Dp::new(18.0),
            navigation_item_height: Dp::new(36.0),
            navigation_item_stride: Dp::new(44.0),
            navigation_item_inset: Dp::new(10.0),
            navigation_item_radius: Dp::new(6.0),
            section_radius: Dp::new(8.0),
            title_x: Dp::new(36.0),
            title_y: Dp::new(32.0),
            title_width: Dp::new(324.0),
            title_height: Dp::new(30.0),
            menu_icon_x: Dp::new(22.0),
            menu_icon_y: Dp::new(18.0),
            menu_icon_size: Dp::new(28.0),
            show_menu_icon: true,
            app_title_x: Dp::new(56.0),
            app_title_y: Dp::new(18.0),
            app_title_width: Dp::new(164.0),
            app_title_height: Dp::new(32.0),
            action_margin: Dp::new(24.0),
            action_height: Dp::new(32.0),
            primary_action_width: Dp::new(72.0),
            secondary_action_width: Dp::new(64.0),
            action_gap: Dp::new(20.0),
            draw_row_separators: true,
        },
    }
}
